// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"STLLA_ScriptCore","status":true,"description":"STLLA共通腳本 v1.2","parameters":{"Follow Mouse":"1"}},
{"name":"FullKeyboard2","status":true,"description":"全按鍵，解決您按鍵不夠的煩惱","parameters":{}},
{"name":"STLLA_BreakoutMain","status":true,"description":"打磚塊遊戲模式 v1.2","parameters":{"Image Path":"img/breakout/","Paddle Image":"","Ball Image":"","EXBall Image":"","Barrier Image":"","Barrier Y":"516","Paddle Rebound SE":"Crossbow,120,85","Wall Rebound SE":"Knock,100,90","Block HP":"1,2,3,4,-1","Block Color":",11,17,2,red","Combo Bonus Increase":"0.2","Block Break Animation":"1","Block Rebound Animation":"2","Count Down SE":"Decision2,130,100","TimeUp SE":"Bell3,100,100","TimeUp Switch":"5","Score Value":"5","Time Value":"6","MaxCombo Value":"7","Score Text":"SCORE：","Combo Text":"COMBO","Time Text":"TIME：","Buff0 Icon":"35,51","Buff1 Icon":"37,53","Buff2 Icon":"38,54","Buff3 Icon":"39,55","Buff4 Icon":"42,58","Buff5 Icon":"46,62","Buff6 Icon":"77","Turn Frame":"60","↓以下為預設值↓":"","Break Effect":"2","Block Display":"0","ItemDrop Rate":"35","Paddle Width":"120","Paddle Height":"15","Paddle SpeedX":"15","Paddle FrictionX":"3","Paddle SpeedY":"3","Paddle FrictionY":"3","Paddle Smash Range":"5","Paddle Down Limit":"516","Paddle Up Limit":"516","Ball Size":"24","Ball Speed":"7","Ball AtkPower":"1"}},
{"name":"STLLA_BreakoutSkill","status":true,"description":"打磚塊系統的技能插件 v1.1","parameters":{"Default MP Recovery":"30","Collider Display":"0"}},
{"name":"STLLA_BreakoutBullets","status":true,"description":"打磚塊系統的飛道管理(進階者用)","parameters":{}},
{"name":"STLLA_BreakoutItem","status":true,"description":"打磚塊系統的道具插件","parameters":{"Default Fall Speed":"5","Default Item Rare":"0","Get Item SE":"Item3,100,100"}},
{"name":"STLLA_BreakoutStage","status":true,"description":"打磚塊的關卡資料","parameters":{}},
{"name":"STLLA_BreakoutEdit","status":false,"description":"打磚塊的關卡編輯器(v1.2)，使用完記得設off","parameters":{"Image Path":"img/breakout/","Load Data":"","Stage Name":"st1_1","Next Stage":"","Front Image":"","Back Image":"","Clear Image":"","Line Color":"black","Stage Width":"816","Stage Height":"624","Block Row":"24","Block Col":"16","Block Width":"34","Block Height":"32","Fall Damage":"1","Remain To Clear":"5","Block Score":"10,20,40,80,160","BGM":"Battle1,100,80","Clear ME":"Victory1,100,90","Lose ME":"Defeat1,100,90","Start CommonEvent":"","Clear CommonEvent":"","Lose CommonEvent":"","Time Limit":"","Item Rare":"0"}}
];
